import { Observable } from 'rxjs';
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class JsondataService {

  //Output Data generated by R Script on API call
  private _urlCcb: string = "http://localhost:89/countCategoriesBins.json";
  private _urlPcc: string = "http://localhost:89/percentiles.json";

  constructor(public http: HttpClient) {
    console.log('JSON data services connected...');
  }

  getCountCatBins(): Observable<any[]> {
    return this.http.get<any[]>(this._urlCcb)
      .map(response => response);
  }

  getPercentiles(): Observable<any[]> {
    return this.http.get<any[]>(this._urlPcc)
      .map(response => response);
  }

}
